baseURL = 'https://blog.chrisworkalx.top/'
languageCode = 'en-us'
title = 'Hi, I am Chris'
theme = "PaperMod"

[pagination]
  pagerSize = 6  # 首页文章每页展示数量

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = true
  ShowToc = true  
  TocOpen = true              # 默认展开目录
  ShowWordCount = true

[params.waline]
  enable = true
  serverURL = "https://waline-demo-sigma.vercel.app/"  # 替换成你的 Waline 部署地址


[[menu.main]]
  identifier = "contact"
  name = "联系我"
  url = "/contact/"
  weight = 50
  pre = "<i class='fas fa-envelope'></i>"
